# Use default url unless a region is provided.
# Region: US, Language: French !a ---> Amazon.com
# Region: France, Language: English !a ---> Amazon.fr
# !afr ---> Amazon.fr
# Note: Some !bangs don't respect the language passed in or
# may not support it (eg they may support pt but not pt-BR)
[[bang]]
    name = "500px"
    favicon = "https://500px.com/favicon.ico"
    triggers = ["500", "500px"]
    [bang.regions]
        default = "https://500px.com/search?q={{{term}}}"

[[bang]]
    name = "800notes"
    favicon = "https://800notes.com/favicon.ico"
    triggers = ["800"]
    [bang.regions]
        default = "https://800notes.com/Phone.aspx/1-{{{term}}}"

[[bang]]
    name = "Amazon"
    favicon = "https://www.amazon.com/favicon.ico"
    triggers = ["a", "amazon"]
    [bang.regions]
        default = "https://www.amazon.com/s/ref=nb_sb_noss?url=search-alias%3Daps&field-keywords={{{term}}}"
        ca = "https://www.amazon.ca/s/ref=nb_sb_noss?url=search-alias%3Daps&field-keywords={{{term}}}"
        fr = "https://www.amazon.fr/s/ref=nb_sb_noss?url=search-alias%3Daps&field-keywords={{{term}}}"
        uk = "https://www.amazon.co.uk/s/ref=nb_sb_noss?url=search-alias%3Daps&field-keywords={{{term}}}"

[[bang]]
    name = "Airbnb"
    favicon = "https://www.airbnb.com/favicon.ico"
    triggers = ["airbnb"]
    [bang.regions]
        default = "https://www.airbnb.com/s/{{{term}}}/all"

[[bang]]
    name = "Algorithmia"
    favicon = "https://algorithmia.com/assets/images/favicon.png"
    triggers = ["algo", "algorithmia"]
    [bang.regions]
        default = "https://algorithmia.com/search?q={{{term}}}"

[[bang]]
    name = "Alibaba"
    favicon = "https://is.alicdn.com/simg/single/icon/favicon.ico"
    triggers = ["baba", "alibaba"]
    [bang.regions]
        default = "https://www.alibaba.com/trade/search?SearchText={{{term}}}"

[[bang]]
    name = "AliExpress"
    favicon = "https://www.aliexpress.com/favicon.ico"
    triggers = ["aliexp", "aliexpress", "ali", "ae", ]
    [bang.regions]
        default = "https://www.aliexpress.com/wholesale?SearchText={{{term}}}"

[[bang]]
    name = "AliExpress Mobile"
    favicon = "https://m.aliexpress.com/img/logo/favicon.ico"
    triggers = ["alim"]
    [bang.regions]
        default = "https://m.aliexpress.com/wholesale/{{{term}}}.html?keywords={{{term}}}"

[[bang]]
    name = "Allrecipes"
    favicon = "https://www.allrecipes.com/favicon.ico"
    triggers = ["ar", "allrecipes", "recipe", "recipes"]
    [bang.regions]
        default = "https://www.allrecipes.com/search/results/?qt=k&wt={{{term}}}&origin=Recipe%20Search%20Results"

[[bang]]
    name = "alternativeTo"
    favicon = "https://alternativeto.net/favicon.ico"
    triggers = ["alto", "altto", "ato", "alt", "alternativeto", "alternative", "a2"]
    [bang.regions]
        default = "https://alternativeto.net/software/{{{term}}}"

[[bang]]
    name = "AMC Networks"
    favicon = "http://www.amc.com/favicon.ico"
    triggers = ["amc"]
    [bang.regions]
        default = "http://www.amc.com/search#q={{{term}}}"

[[bang]]
    name = "AngelList"
    favicon = "https://assets.angel.co/assets/icons/angellist-e1decb2fb69dc221e2dd4ad5f749797e28b3e9e92957e0f161b8e64d5a8a74c8.ico"
    triggers = ["angellist"]
    [bang.regions]
        default = "https://angel.co/search?q={{{term}}}"

[[bang]]
    name = "Answers"
    favicon = "https://www.answers.com/favicon.ico"
    triggers = ["answers"]
    [bang.regions]
        default = "https://www.answers.com/search?q={{{term}}}"

[[bang]]
    name = "Aol"
    favicon = "https://s.blogsmithmedia.com/www.aol.com/assets-h7f98b93826355b88b8b2513a24166879/images/favicon/favicon-16x16.png?h=adfa9c2f0e5396a0b113422f4cf312aa"
    triggers = ["aol"]
    [bang.regions]
        default = "https://search.aol.com/aol/search?s_chn=prt_bon&q={{{term}}}&s_it=comsearch"

[[bang]]
    name = "Apple"
    favicon = "https://www.apple.com/favicon.ico"
    triggers = ["apple"]
    [bang.regions]
        default = "https://www.apple.com/search/{{{term}}}"

[[bang]]
    name = "Apple Developer Forums"
    favicon = "https://www.apple.com/favicon.ico"
    triggers = ["adf", "appledevforum"]
    [bang.regions]
        default = "https://forums.developer.apple.com/search.jspa?q={{{term}}}"

[[bang]]
    name = "Apple Developer"
    favicon = "https://www.apple.com/favicon.ico"
    triggers = ["devapple", "appledev", "cocoa", "adev", "adc"]
    [bang.regions]
        default = "https://developer.apple.com/search/?q={{{term}}}"

[[bang]]
    name = "Apple Discussions"
    favicon = "https://www.apple.com/favicon.ico"
    triggers = ["applediscuss"]
    [bang.regions]
        default = "https://discussions.apple.com/search.jspa?peopleEnabled=true&userID=&containerType=&container=&spotlight=true&q={{{term}}}"

[[bang]]
    name = "Apple Support"
    favicon = "https://www.apple.com/favicon.ico"
    triggers = ["applesupport"]
    [bang.regions]
        default = "https://support.apple.com/kb/index?page=search&q={{{term}}}&product=&doctype=&currentPage=1&includeArchived=false&locale=en_US&src=support_site.kbase.search.searchresults"

[[bang]]
    name = "Archive.is"
    favicon = "https://archive.is/favicon.ico"
    triggers = ["archiveis", "ais"]
    [bang.regions]
        default = "https://archive.fo/search/?q={{{term}}}"

[[bang]]
    name = "Ask Ubuntu"
    favicon = "https://cdn.sstatic.net/Sites/askubuntu/img/favicon.ico"
    triggers = ["askubnt", "asku", "askubuntu"]
    [bang.regions]
        default = "https://askubuntu.com/search?q={{{term}}}"

[[bang]]
    name = "Ask.com"
    favicon = "http://www.search.ask.com/favicon.ico"
    triggers = ["ask", "jeeves"]
    [bang.regions]
        default = "http://www.search.ask.com/web?q={{{term}}}"

[[bang]]
    name = "AutoZone"
    favicon = "https://www.autozone.com/favicon.ico"
    triggers = ["azo", "autozone"]
    [bang.regions]
        default = "https://www.autozone.com/searchresult?searchText={{{term}}}"

[[bang]]
    name = "AWS Documentation"
    favicon = "https://aws.amazon.com/favicon.ico"
    triggers = ["aws"]
    [bang.regions]
        default = "https://aws.amazon.com/search/?searchQuery={{{term}}}"

[[bang]]
    name = "A-ZFonts"
    favicon = "https://www.azfonts.net/images/favicon.ico"
    triggers = ["azfonts"]
    [bang.regions]
        default = "https://www.azfonts.net/search.html?query={{{term}}}"

[[bang]]
    name = "AZLyrics"
    favicon = "https://www.azlyrics.com/favicon.ico"
    triggers = ["azl", "azlyrics"]
    [bang.regions]
        default = "https://search.azlyrics.com/search.php?q={{{term}}}"

[[bang]]
    name = "Bing"
    favicon = "https://www.bing.com/favicon.ico"
    triggers = ["b", "bing"]
    [bang.regions]
        default = "https://www.bing.com/search?q={{{term}}}"

[[bang]]
    name = "Bing Images"
    favicon = "https://www.bing.com/favicon.ico"
    triggers = ["bi", "bingimages"]
    [bang.regions]
        default = "https://www.bing.com/images/search?q={{{term}}}"
    
[[bang]]
    name = "Bitbucket"
    favicon = "https://bitbucket.org/favicon.ico"
    triggers = ["bb", "bitbucket"]
    [bang.regions]
        default = "https://bitbucket.org/repo/all/?name={{{term}}}"

[[bang]]
    name = "CNBC"
    favicon = "https://www.cnbc.com/favicon.ico"
    triggers = ["cnbc"]
    [bang.regions]
        default = "http://search.cnbc.com/main.do?target=all&keywords={{{term}}}"

[[bang]]
    name = "GitHub"
    favicon = "https://github.com/favicon.ico"
    triggers = ["gh", "git", "github"]
    [bang.regions]
        default = "https://github.com/search?q={{{term}}}&type=Everything&repo=&langOverride=&start_value=1"

[[bang]]
    name = "eBay"
    favicon = "https://www.ebay.com/favicon.ico"
    triggers = ["e", "ebay"]
    [bang.regions]
        default = "https://www.ebay.com/sch/items/?_nkw={{{term}}}&_sacat=&_ex_kw=&_mPrRngCbx=1&_udlo=&_udhi=&_sop=12&_fpos=&_fspt=1&_sadis=&LH_CAds=&rmvSB=true"

[[bang]]
    name = "Genius"
    favicon = "http://genius.com/favicon.ico"
    triggers = ["genius"]
    [bang.regions]
        default = "https://genius.com/search?q={{{term}}}"

[[bang]]
    name = "Giphy"
    favicon = "https://giphy.com/favicon.ico"
    triggers = ["giphy"]
    [bang.regions]
        default = "https://giphy.com/search/{{{term}}}"

[[bang]]
    name = "Google"
    favicon = "https://www.google.com/favicon.ico"
    triggers = ["g", "google"]
    [bang.regions]
        default = "https://encrypted.google.com/search?hl={{{lang}}}&q={{{term}}}"
        ca = "https://www.google.ca/search?q={{{term}}}"
		fr = "https://www.google.fr/search?hl={{{lang}}}&q={{{term}}}"
		ru = "https://www.google.ru/search?hl={{{lang}}}&q={{{term}}}"

[[bang]]
    name = "Google France"
    favicon = "https://www.google.com/favicon.ico"
    triggers = ["gfr", "googlefr"]
    [bang.regions]
        default = "https://www.google.fr/search?hl={{{lang}}}&q={{{term}}}"

[[bang]]
    name = "Google Images"
    favicon = "https://www.google.com/favicon.ico"
    triggers = ["gi"]
    [bang.regions]
        default = "https://www.google.com/search?q={{{term}}}&source=lnms&tbm=isch"

[[bang]]
    name = "Google Russia"
    favicon = "https://www.google.com/favicon.ico"
    triggers = ["gru", "googleru"]
    [bang.regions]
        default = "https://www.google.ru/search?hl={{{lang}}}&q={{{term}}}"

[[bang]]
    name = "Google Scholar"
    favicon = "https://www.google.com/favicon.ico"
    triggers = ["googlescholar"]
    [bang.regions]
        default = "https://scholar.google.com/scholar?hl={{{lang}}}&q={{{term}}}"

[[bang]]
    name = "Google Translate"
    favicon = "https://www.google.com/favicon.ico"
    triggers = ["gt", "googletranslate"]
    [bang.regions]
        default = "https://translate.google.com/#auto/en/{{{term}}}"

[[bang]]
    name = "Hacker News"
    favicon = "https://news.ycombinator.com/favicon.ico"
    triggers = ["hn", "hackernews"]
    [bang.regions]
        default = "https://hn.algolia.com/?query={{{term}}}&sort=byPopularity&prefix&page=0&dateRange=all&type=story"

[[bang]]
    name = "Hulu"
    favicon = "http://www.hulu.com/favicon.ico"
    triggers = ["hulu"]
    [bang.regions]
        default = "https://www.hulu.com/search?query={{{term}}}"

[[bang]]
    name = "IFTTT"
    favicon = "https://ifttt.com/favicon.ico"
    triggers = ["ifttt"]
    [bang.regions]
        default = "https://ifttt.com/search/query/{{{term}}}"

[[bang]]
    name = "IMDb"
    favicon = "https://ia.media-imdb.com/images/G/01/imdb/images/favicon-2165806970"
    triggers = ["imdb"]
    [bang.regions]
        default = "http://www.imdb.com/find?q={{{term}}}&s=all"

[[bang]]
    name = "Instagram"
    favicon = "https://instagram.com/favicon.ico"
    triggers = ["instagram", "ig"]
    [bang.regions]
        default = "https://www.instagram.com/explore/tags/{{{term}}}"

[[bang]]
    name = "Internet Archive"
    favicon = "https://archive.org/favicon.ico"
    triggers = ["archive", "iarchive", "archiveweb"]
    [bang.regions]
        default = "https://archive.org/search.php?query={{{term}}}"

[[bang]]
    name = "jQuery"
    favicon = "https://jquery.com/jquery-wp-content/themes/jquery.com/i/favicon.ico"
    triggers = ["jquery"]
    [bang.regions]
        default = "https://api.jquery.com/?ns0=1&s={{{term}}}"

[[bang]]
    name = "jQuery UI"
    favicon = "https://jqueryui.com/jquery-wp-content/themes/jqueryui.com/i/favicon.ico"
    triggers = ["jqu", "jqui", "jqueryui"]
    [bang.regions]
        default = "https://jqueryui.com/?s={{{term}}}"

[[bang]]
    name = "LinkedIn"
    favicon = "https://www.linkedin.com/favicon.ico"
    triggers = ["linkedin", "li"]
    [bang.regions]
        default = "https://www.linkedin.com/search/results/index/?keywords={{{term}}}"

[[bang]]
    name = "Medium"
    favicon = "https://medium.com/favicon.ico"
    triggers = ["med", "medium"]
    [bang.regions]
        default = "https://medium.com/search?q={{{term}}}"

[[bang]]
    name = "Movie DB"
    favicon = "https://www.themoviedb.org/favicon.ico"
    triggers = ["moviedb"]
    [bang.regions]
        default = "https://www.themoviedb.org/search?query={{{term}}}"

[[bang]]
    name = "New York Times"
    favicon = "http://www.nytimes.com/favicon.ico"
    triggers = ["nyt", "nytimes", "newyorktimes"]
    [bang.regions]
        default = "http://query.nytimes.com/search/sitesearch/#/{{{term}}}/"
        
[[bang]]
    name = "Reddit"
    favicon = "https://www.reddit.com/favicon.ico"
    triggers = ["reddit"]
    [bang.regions]
        default = "https://www.reddit.com/search?q={{{term}}}&restrict_sr=&sort=relevance&t=all"

[[bang]]
    name = "Rotten Tomatoes"
    favicon = "https://www.rottentomatoes.com/favicon.ico"
    triggers = ["rt", "rottentomatoes", "rottentomato"]
    [bang.regions]
        default = "https://www.rottentomatoes.com/search/?search={{{term}}}"
        
[[bang]]
    name = "SEC"
    favicon = "https://www.sec.gov/favicon.ico"
    triggers = ["sec", "edgar"]
    [bang.regions]
        default = "https://www.sec.gov/cgi-bin/browse-edgar?CIK={{{term}}}&owner=exclude&action=getcompany"

[[bang]]
    name = "Stack Exchange"
    favicon = "https://cdn.sstatic.net/Sites/stackexchange/img/favicon.ico"
    triggers = ["se", "sx", "stackexchange"]
    [bang.regions]
        default = "https://stackexchange.com/search?q={{{term}}}"

[[bang]]
    name = "Stack Overflow"
    favicon = "https://cdn.sstatic.net/Sites/stackoverflow/img/favicon.ico"
    triggers = ["so", "stackoverflow"]
    [bang.regions]
        default = "https://stackoverflow.com/search?q={{{term}}}"
        
[[bang]]
    name = "Steam"
    favicon = "https://store.steampowered.com/favicon.ico"
    triggers = ["steam"]
    [bang.regions]
        default = "http://store.steampowered.com/search/?term={{{term}}}"

[[bang]]
    name = "Subreddit"
    favicon = "https://www.reddit.com/favicon.ico"
    triggers = ["sr", "subreddit", "sreddit"]
    [bang.regions]
        default = "https://www.reddit.com/r/{{{term}}}"

[[bang]]
    name = "TV Database"
    favicon = "https://www.thetvdb.com/favicon.ico"
    triggers = ["tvdb"]
    [bang.regions]
        default = "https://www.thetvdb.com/?string={{{term}}}&tab=listseries&function=Search"

[[bang]]
    name = "Twitter"
    favicon = "https://twitter.com/favicon.ico"
    triggers = ["t", "tw", "twitter"]
    [bang.regions]
        default = "https://twitter.com/search?q={{{term}}}"

[[bang]]
    name = "Twitch"
    favicon = "https://static.twitchcdn.net/assets/favicon-75270f9df2b07174c23c.ico"
    trigggers = ["twitch"]
    [bang.regions]
        default = "https://www.twitch.tv/{{{term}}}"

[[bang]]
    name = "Ultimate Guitar Tabs"
    favicon = "https://www.ultimate-guitar.com/static/_img/bootstrap/ug/img/favicon.ico"
    triggers = ["tabs", "ultimateguitar"]
    [bang.regions]
        default = "https://www.ultimate-guitar.com/search.php?search_type=title&value={{{term}}}"

[[bang]]
    name = "Urban Dictionary"
    favicon = "https://www.urbandictionary.com/favicon.ico"
    triggers = ["u", "ud", "urbandictionary"]
    [bang.regions]
        default = "https://www.urbandictionary.com/define.php?term={{{term}}}"

[[bang]]
    name = "Wall Street Journal"
    favicon = "http://online.wsj.com/favicon.ico"
    triggers = ["wsj", "wallstreetjournal"]
    [bang.regions]
        default = "https://www.wsj.com/search/term.html?KEYWORDS={{{term}}}&isAdvanced=true&daysback=90d&andor=AND&sort=date-desc&source=wsjarticle,wsjblogs,wsjvideo,sitesearch,press,newswire"

[[bang]]
    name = "Wayback Machine"
    favicon = "https://web.archive.org/static/images/archive.ico"
    triggers = ["archived", "wbm", "save", "wayback", "waybackmachine"]
    [bang.regions]
        default = "https://web.archive.org/web/*/{{{term}}}"

[[bang]]
    name = "WeatherBug"
    favicon = "https://www.weatherbug.com/img/favicon-32x32.png"
    triggers = ["weatherbug"]
    [bang.regions]
        default = "https://www.weatherbug.com/weather-forecast/now/{{{term}}}"

[[bang]]
    name = "The Weather Channel"
    favicon = "https://weather.com/weather/assets/favicon.1acd6ad0f84c999b39c434f6bda4e29f.ico"
    triggers = ["wc", "weatherchannel"]
    [bang.regions]
        default = "https://weather.com/weather/today/l/{{{term}}}"

[[bang]]
    # I think these need to be mapped to languages, not regions...
    name = "Wikipedia"
    favicon = "https://en.wikipedia.org/favicon.ico"
    triggers = ["w", "wikipedia"]
    functions = ["wikipediaCanonical"]
    [bang.regions]
        default = "https://en.wikipedia.org/wiki/{{{term}}}"
        es = "https://es.wikipedia.org/wiki/{{{term}}}"
        de = "https://de.wikipedia.org/wiki/{{{term}}}"
        fr = "https://fr.wikipedia.org/wiki/{{{term}}}"

[[bang]]
    name = "Wolfram|Alpha"
    favicon = "https://www.wolframalpha.com/favicon.ico"
    triggers = ["wa", "wolframalpha"]
    [bang.regions]
        default = "https://www.wolframalpha.com/input/?i={{{term}}}"

[[bang]]
    name = "Yahoo"
    favicon = "https://www.yahoo.com/favicon.ico"
    triggers = ["y", "yahoo"]
    [bang.regions]
        default = "https://search.yahoo.com/search?p={{{term}}}"
        
[[bang]]
    name = "Yahoo Finance"
    favicon = "https://www.yahoo.com/favicon.ico"
    triggers = ["yf", "yahoofinance"]
    [bang.regions]
        default = "https://finance.yahoo.com/quote/{{{term}}}"
       
[[bang]]
    name = "Yahoo Finance Charts"
    favicon = "https://www.yahoo.com/favicon.ico"
    triggers = ["yfc"]
    [bang.regions]
        default = "https://finance.yahoo.com/chart/{{{term}}}"

[[bang]]
    name = "Yahoo Finance Profile"
    favicon = "https://www.yahoo.com/favicon.ico"
    triggers = ["yfp"]
    [bang.regions]
        default = "https://finance.yahoo.com/quote/{{{term}}}/profile"
        
[[bang]]
    name = "Yahoo Finance Stats"
    favicon = "https://www.yahoo.com/favicon.ico"
    triggers = ["yfs"]
    [bang.regions]
        default = "https://finance.yahoo.com/quote/{{{term}}}/key-statistics"

[[bang]]
    name = "Youtube"
    favicon = "https://youtube.com/favicon.ico"
    triggers = ["yt", "youtube"]
    [bang.regions]
        default = "https://www.youtube.com/results?search_query={{{term}}}"